services:
  mysql:
    container_name: 'guide-mysql-activitatsnoevaluables'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=products'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'